---
apiVersion: v1
kind: Service
metadata:
  name: websocket-testcase
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: websocket-testcase
  namespace: websocket-testcase-ns
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30004
  selector:
    name: websocket-testcase
